@echo off
echo Fixing monitor.tsx file...

echo import React from "react"; > "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo import { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   View, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   Text, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   TouchableOpacity, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   Platform, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   StyleSheet, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   Alert, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo } from "react-native"; >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo import { useSafeAreaInsets } from "react-native-safe-area-context"; >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo import { Link } from 'expo-router'; >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo import { Ionicons } from '@expo/vector-icons'; >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo import { useThemeColor } from '../../hooks/useThemeColor'; >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo export default function MonitorScreen() { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   const insets = useSafeAreaInsets(); >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   const highlightColor = useThemeColor({}, 'tint'); >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   const textColor = useThemeColor({}, 'text'); >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   return ( >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     ^<View style={[styles.container, { paddingTop: insets.top }]}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^<Text style={styles.title}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         Fraud Monitoring >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^<Text style={styles.description}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         Choose a monitoring service below to detect and protect against fraudulent activity. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^<View style={styles.cardsContainer}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         {/* SMS Monitoring Card */} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^<Link href="/sms-monitor" asChild^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<TouchableOpacity  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             style={styles.card} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             activeOpacity={0.7} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<View style={[styles.iconContainer, { backgroundColor: highlightColor }]}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^<Ionicons name="chatbubble-outline" size={28} color="#fff" /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<View style={styles.cardContent}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^<Text style={styles.cardTitle}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo                 SMS Monitoring >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^<Text style={styles.cardDescription}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo                 Automatically scan incoming SMS messages for potential fraud. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               {Platform.OS !== 'android' ^&^& ( >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo                 ^<View style={styles.warningBadge}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo                   ^<Text style={styles.warningText}^>iOS not supported^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo                 ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               )} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Ionicons  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               name="chevron-forward"  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               size={24}  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               color={textColor} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               style={styles.cardArrow} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^</TouchableOpacity^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^</Link^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         {/* Email Monitoring Card - Coming Soon */} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^<TouchableOpacity  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           style={[styles.card, styles.disabledCard]} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           activeOpacity={0.7} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           onPress={() =^> alert('Email monitoring coming soon!')} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<View style={[styles.iconContainer, { backgroundColor: 'gray' }]}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Ionicons name="mail-outline" size={28} color="#fff" /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<View style={styles.cardContent}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Text style={styles.cardTitle}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               Email Monitoring >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Text style={styles.cardDescription}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               Scan emails for phishing attempts and fraudulent links. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<View style={styles.comingSoonBadge}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^<Text style={styles.comingSoonText}^>Coming Soon^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<Ionicons  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             name="chevron-forward"  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             size={24}  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             color="gray" >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             style={styles.cardArrow} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^</TouchableOpacity^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         {/* Call Monitoring Card - Coming Soon */} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^<TouchableOpacity  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           style={[styles.card, styles.disabledCard]} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           activeOpacity={0.7} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           onPress={() =^> alert('Call monitoring coming soon!')} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<View style={[styles.iconContainer, { backgroundColor: 'gray' }]}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Ionicons name="call-outline" size={28} color="#fff" /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<View style={styles.cardContent}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Text style={styles.cardTitle}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               Call Monitoring >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<Text style={styles.cardDescription}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               Identify potentially fraudulent calls and scam numbers. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^<View style={styles.comingSoonBadge}^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo               ^<Text style={styles.comingSoonText}^>Coming Soon^</Text^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           ^<Ionicons  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             name="chevron-forward"  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             size={24}  >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             color="gray" >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo             style={styles.cardArrow} >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo           /^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo         ^</TouchableOpacity^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo       ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     ^</View^> >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   ); >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo } >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo. >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo const styles = StyleSheet.create({ >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   container: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     flex: 1, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     padding: 16, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     backgroundColor: "#f9fafb", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   title: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 24, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontWeight: "bold", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#111827", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginBottom: 12, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   description: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 16, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#4b5563", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginBottom: 24, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     lineHeight: 22, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   cardsContainer: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     flex: 1, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   card: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     backgroundColor: "#ffffff", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     borderRadius: 12, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     padding: 16, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginBottom: 16, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     flexDirection: "row", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     alignItems: "center", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     shadowColor: "#000", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     shadowOffset: { width: 0, height: 1 }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     shadowOpacity: 0.05, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     shadowRadius: 3, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     elevation: 1, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   disabledCard: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     opacity: 0.8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   iconContainer: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     width: 50, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     height: 50, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     borderRadius: 25, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     justifyContent: "center", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     alignItems: "center", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   cardContent: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     flex: 1, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     paddingHorizontal: 14, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   cardTitle: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 18, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontWeight: "bold", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#111827", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginBottom: 4, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   cardDescription: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 14, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#4b5563", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     lineHeight: 20, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   cardArrow: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginLeft: 8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   warningBadge: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     backgroundColor: "#fef3c7", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     paddingHorizontal: 8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     paddingVertical: 4, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     borderRadius: 999, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     alignSelf: "flex-start", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginTop: 8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   warningText: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#d97706", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 12, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontWeight: "500", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   comingSoonBadge: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     backgroundColor: "#e5e7eb", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     paddingHorizontal: 8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     paddingVertical: 4, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     borderRadius: 999, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     alignSelf: "flex-start", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     marginTop: 8, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   comingSoonText: { >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     color: "#6b7280", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontSize: 12, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo     fontWeight: "500", >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo   }, >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"
echo }); >> "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"

copy "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed" "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx"
del "d:\Fraud-Shield\frontend\my-app\app\(tabs)\monitor.tsx.fixed"

echo Done!
